### ISSUE TITLE
add this meta tag to you head section

### ISSUE THREAD

**Issue by rimmesbe** [isaac-chou/colmar#1]
Always add this meta tag to your `<head>` section when using media queries:
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
This will ensure that the media queries register on all size devices.
https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

https://github.com/isaac-chou/colmar/blob/master/index.html#L3

**Comment by isaac-chou** [comment]
Thanks for the tip. I appreciate it :)
