### ISSUE TITLE
html looks good

### ISSUE THREAD

**Issue by rimmesbe** [isaac-chou/colmar#4]
Your html itself does look good. If you want to make it even better start incorporating even more semantic tags as there are many. Take a look at this article:
https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

https://github.com/isaac-chou/colmar/blob/master/index.html

**Comment by isaac-chou** [comment]
Thanks. I will read up on it.
