### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [isaac-chou/colmar#5]
Grade: Satisfactory

Summary: Nice job on this project, the site looks very good on desktop and mobile. You used a lot of good techniques and kept your code well organized. Take a look at the issues I created as they will point out some best practices and new techniques you can start using. The main issue I see is just a lot of extra html for mobile. The purpose of "responsive" design is so you don't have to do this. You can just adjust minimal styling so better fit the smaller screen. Hope you enjoyed the course!

**Comment by isaac-chou** [comment]
Thank you for the feedback. I DID enjoy the course. I have to say that sometimes the instructions in the lessons sections was not very clear on what I had to do, resulting in a lot of time spent deciphering the intent. I encountered this more on the last 2 modules.
